log("Startup")
log("Startup By Lorki")
local probableJsonStr = root.functions_transcoding.f_fromBase64(getParameter("2"))
matchDescription = fromJson(probableJsonStr)
if matchDescription == nil or #matchDescription ~= 2 then
  replayLoadingId = root.system_loader.f_add(getParameter("2"))
  assert(replayLoadingId ~= nil)
  matchDescription = nil
end
root.f_loadProject()
if root.project ~= nil then
  local data = {
    unitNames = {
      localize("<*unitName0>"),
      localize("<*unitName1>"),
      localize("<*unitName2>"),
      localize("<*unitName3>"),
      localize("<*unitName4>"),
      localize("<*unitName5>"),
      localize("<*unitName6>"),
      localize("<*unitName7>"),
      localize("<*unitName8>"),
      localize("<*unitName9>"),
      localize("<*unitName10>"),
      localize("<*unitName11>"),
      localize("<*unitName12>"),
      localize("<*unitName13>"),
      localize("<*unitName14>"),
      localize("<*unitName15>"),
      localize("<*unitName16>"),
      localize("<*unitName17>"),
      localize("<*unitName18>"),
      localize("<*unitName19>"),
      localize("<*unitName20>"),
      localize("<*unitName21>"),
      localize("<*unitName22>"),
      localize("<*unitName23>"),
      localize("<*unitName24>"),
      localize("<*unitName25>"),
      localize("<*unitName26>"),
      localize("<*unitName27>"),
      localize("<*unitName28>"),
      localize("<*unitName29>"),
      localize("<*unitName30>"),
      localize("<*unitName31>"),
      localize("<*unitName32>"),
      localize("<*unitName33>"),
      localize("<*unitName34>"),
      localize("<*unitName35>"),
      localize("<*unitName36>"),
      localize("<*unitName37>"),
      localize("<*unitName38>"),
      localize("<*unitName39>"),
      localize("<*unitName40>"),
      localize("<*unitName41>"),
      localize("<*unitName42>"),
      localize("<*unitName43>"),
      localize("<*unitName44>"),
      localize("<*unitName45>"),
      localize("<*unitName46>"),
      localize("<*unitName47>"),
      localize("<*unitName48>"),
      localize("<*unitName49>"),
      localize("<*unitName50>"),
      localize("<*unitName51>"),
      localize("<*unitName52>"),
      localize("<*unitName53>"),
      localize("<*unitName54>"),
      localize("<*unitName55>"),
      localize("<*unitName56>"),
      localize("<*unitName57>"),
      localize("<*unitName58>"),
      localize("<*unitName59>"),
      localize("<*unitName60>"),
      localize("<*unitName61>"),
      localize("<*unitName62>"),
      localize("<*unitName63>"),
      localize("<*unitName64>"),
      localize("<*unitName65>"),
      localize("<*unitName66>"),
      localize("<*unitName67>"),
      localize("<*unitName68>"),
      localize("<*unitName69>"),
      localize("<*unitName70>"),
      localize("<*unitName71>"),
      localize("<*unitName72>"),
      localize("<*unitName73>"),
      localize("<*unitName74>"),
      localize("<*unitName75>"),
      localize("<*unitName76>"),
      localize("<*unitName77>"),
      localize("<*unitName78>"),
      localize("<*unitName79>"),
      localize("<*unitName80>"),
      localize("<*unitName81>"),
      localize("<*unitName82>"),
      localize("<*unitName83>"),
      localize("<*unitName84>"),
      localize("<*unitName85>"),
      localize("<*unitName86>"),
      localize("<*unitName87>"),
      localize("<*unitName88>"),
      localize("<*unitName89>"),
      localize("<*unitName90>"),
      localize("<*unitName91>"),
      localize("<*unitName92>"),
      localize("<*unitName93>"),
      localize("<*unitName94>"),
      localize("<*unitName95>"),
      localize("<*unitName96>"),
      localize("<*unitName97>"),
      localize("<*unitName98>"),
      localize("<*unitName99>"),
      localize("<*unitName100>"),
      localize("<*unitName101>"),
      localize("<*unitName102>"),
      localize("<*unitName103>"),
      localize("<*unitName104>"),
      localize("<*unitName105>"),
      localize("<*unitName106>"),
      localize("<*unitName107>"),
      localize("<*unitName108>"),
      localize("<*unitName109>"),
      localize("<*unitName110>"),
      localize("<*unitName111>"),
      localize("<*unitName112>"),
      localize("<*unitName113>"),
      localize("<*unitName114>"),
      localize("<*unitName115>"),
      localize("<*unitName116>"),
      localize("<*unitName117>"),
      localize("<*unitName118>"),
      localize("<*unitName119>"),
      localize("<*unitName120>"),
      localize("<*unitName121>")
    },
    envTagNames = {
      localize("<*envTag/0>"),
      localize("<*envTag/1>"),
      localize("<*envTag/2>"),
      localize("<*envTag/3>"),
      localize("<*envTag/4>"),
      localize("<*envTag/5>"),
      localize("<*envTag/6>"),
      localize("<*envTag/7>"),
      localize("<*envTag/8>"),
      localize("<*envTag/9>")
    },
    envSearchTagNames = {
      localize("<*envSearchTag/0>"),
      localize("<*envSearchTag/1>"),
      localize("<*envSearchTag/2>"),
      localize("<*envSearchTag/3>"),
      localize("<*envSearchTag/4>"),
      localize("<*envSearchTag/5>"),
      localize("<*envSearchTag/6>"),
      localize("<*envSearchTag/7>"),
      localize("<*envSearchTag/8>"),
      localize("<*envSearchTag/9>"),
      localize("<*envSearchTag/10>"),
      localize("<*envSearchTag/11>"),
      localize("<*envSearchTag/12>"),
      localize("<*envSearchTag/13>"),
      localize("<*envSearchTag/14>"),
      localize("<*envSearchTag/15>")
    },
    unitTagNames = {
      localize("<*unitTag/0>"),
      localize("<*unitTag/1>"),
      localize("<*unitTag/2>"),
      localize("<*unitTag/3>"),
      localize("<*unitTag/4>"),
      localize("<*unitTag/5>"),
      localize("<*unitTag/6>"),
      localize("<*unitTag/7>"),
      localize("<*unitTag/8>"),
      localize("<*unitTag/9>"),
      localize("<*unitTag/10>"),
      localize("<*unitTag/11>"),
      localize("<*unitTag/12>"),
      localize("<*unitTag/13>"),
      localize("<*unitTag/14>"),
      localize("<*unitTag/15>"),
      localize("<*unitTag/16>"),
      localize("<*unitTag/17>"),
      localize("<*unitTag/18>"),
      localize("<*unitTag/19>"),
      localize("<*unitTag/20>"),
      localize("<*unitTag/21>"),
      localize("<*unitTag/22>"),
      localize("<*unitTag/23>"),
      localize("<*unitTag/24>"),
      localize("<*unitTag/25>"),
      localize("<*unitTag/26>"),
      localize("<*unitTag/27>"),
      localize("<*unitTag/28>"),
      localize("<*unitTag/29>"),
      localize("<*unitTag/30>"),
      localize("<*unitTag/31>")
    },
    unitSearchTagNames = {
      localize("<*unitSearchTag/0>"),
      localize("<*unitSearchTag/1>"),
      localize("<*unitSearchTag/2>"),
      localize("<*unitSearchTag/3>"),
      localize("<*unitSearchTag/4>"),
      localize("<*unitSearchTag/5>"),
      localize("<*unitSearchTag/6>"),
      localize("<*unitSearchTag/7>"),
      localize("<*unitSearchTag/8>"),
      localize("<*unitSearchTag/9>"),
      localize("<*unitSearchTag/10>"),
      localize("<*unitSearchTag/11>"),
      localize("<*unitSearchTag/12>"),
      localize("<*unitSearchTag/13>"),
      localize("<*unitSearchTag/14>"),
      localize("<*unitSearchTag/15>")
    },
    passabilityLevels = {
      localize("<*passabilityLevel0>"),
      localize("<*passabilityLevel1>"),
      localize("<*passabilityLevel2>"),
      localize("<*passabilityLevel3>"),
      localize("<*passabilityLevel4>"),
      localize("<*passabilityLevel5>"),
      localize("<*passabilityLevel6>")
    },
    upgradeScriptNames = {"Damage up"},
    upgradeScriptParameters = {"mult=100"},
    renderFont = "Roboto-Medium",
    interfaceRunScript = 6,
    createEmitterScript = 5,
    createUnitScript = 3,
    createEnvScript = 4,
    placerAppearance = 65,
    placerScale = 100
  }
  root.interface.f_create("/project/Developer/interface", "development", 1, 1, "data", toJson(data))
  root.interface_development_priority = 90
  root.interface_development_active = true
  root.interface.f_create("/project/Developer/console", "devConsole", 1, 1)
  root.interface_devConsole_priority = 95
  root.interface_devConsole_active = true
end
